# Generated by Django 5.2.4 on 2025-07-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_conversation_admin_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
